
// JS

require('./js/app')
require('./js/routes')

require('./modules/admin/admin-orgs')
require('./modules/admin/admin-users')
require('./modules/admin/admin')
require('./modules/comments/comments')
require('./modules/confirm/confirm')
require('./modules/forms/avalanche-trigger-select')
require('./modules/header/header')
require('./modules/location-select-modal/location-select-modal')
require('./modules/map/layers')
require('./modules/map/linear-graph')
require('./modules/map/terrain-layer')
require('./modules/map/map-directive')
require('./modules/map/map')
require('./modules/map/ob-search')
require('./modules/map/rose-graph')
require('./modules/map/route-planning')
require('./modules/map/terrain-visualization')
require('./modules/map-search/map-search')
require('./modules/observations/observations')
require('./modules/observations/preview')
require('./modules/organizations/organizations')
require('./modules/publish-modal/modal')
require('./modules/register-device-modal/modal')
require('./modules/snowpit-editor/snowpit-canvas')
require('./modules/snowpit-editor/snowpit-constants')
require('./modules/snowpit-editor/snowpit-editor')
require('./modules/snowpit-editor/snowpit-export')
require('./modules/snowpit-editor/snowpit-graphs')
require('./modules/snowpit-editor/snowpit-stability')
require('./modules/snowpit-editor/snowpit-views')
require('./modules/sp-profile-upload/modal')
require('./modules/sp-profiles/sp-profile-graphs')
require('./modules/user/forgot-password')
require('./modules/user/login')
require('./modules/user/register')
require('./modules/user/reset-password')
require('./modules/user/settings')

require('./js/services/global')
require('./js/services/observations-service')
require('./js/services/routes-service')

require('./js/directives/datepicker')
require('./js/directives/fileupload')
require('./js/directives/grain-select')
require('./js/directives/input-direction')
require('./js/directives/misc')
require('./js/directives/textarea-autosize')
require('./js/directives/timeinput')
require('./js/directives/validation')

require('./js/init')

if (__PROD__) {
    require('./vendor/raven/raven.min.js')
}

if (__STAGE__ || __PROD__) {
    require('./js/analytics')
}

// HTML

require('./js/directives/grain-select.html')
require('./js/directives/datepicker.html')
require('./js/directives/fileupload.html')
require('./js/directives/input-direction-range.html')
require('./js/directives/input-direction.html')
require('./modules/404/404.html')
require('./modules/admin/admin.html')
require('./modules/admin/orgs.html')
require('./modules/admin/users.html')
require('./modules/comments/comments-new.html')
require('./modules/confirm/confirm.html')
require('./modules/firmware-update/SP1update.html')
require('./modules/forms/avalanche-trigger.html')
require('./modules/forms/avalanche-trigger-select.html')
require('./modules/forms/datepicker.html')
require('./modules/forms/direction-select.html')
require('./modules/forms/grain-type-select.html')
require('./modules/forms/location-select.html')
require('./modules/forms/number.html')
require('./modules/forms/radiobuttons-nullable.html')
require('./modules/forms/trend-select.html')
require('./modules/header/header.html')
require('./modules/location-select-modal/location-select-modal.html')
require('./modules/map/map-directive.html')
require('./modules/map/map.html')
require('./modules/map/ob-search.html')
require('./modules/map/observation-map-popup.html')
require('./modules/map/route-planning.html')
require('./modules/map-search/map-search.html')
require('./modules/observations/new.html')
require('./modules/observations/preview.html')
require('./modules/organizations/new.html')
require('./modules/organizations/view.html')
require('./modules/profiles/preview-side.html')
require('./modules/publish-modal/modal.html')
require('./modules/register-device-modal/modal.html')
require('./modules/snowpit-editor/snowpit-stability.html')
require('./modules/snowpit-editor/snowpit.html')
require('./modules/sp-profile-upload/button.html')
require('./modules/sp-profile-upload/modal.html')
require('./modules/support/support.html')
require('./modules/user/forgot-password.html')
require('./modules/user/login.html')
require('./modules/user/register-new.html')
require('./modules/user/reset-password.html')
require('./modules/user/settings.html')
